In [1]:
# from database_handler import *
# from lookups import *
# from logging_handler import show_error_message
# from datetime import time, datetime

# db_session = create_connection()
# refresh_connection(db_session=db_session)
# close_connection(db_session)

In [1]:
from database_handler import read_data_as_dataframe, create_connection
from lookups import Sources, InputTypes
# db_session = create_connection()
# df = read_data_as_dataframe(InputTypes.CSV, Sources.listings_source.value)
df = read_data_as_dataframe(InputTypes.CSV, 'csv_files\listings.csv')

In [5]:
df['number_of_reviews'].dtype

dtype('int64')

In [2]:
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,6,https://www.airbnb.com/rooms/6,20230918050343,2023-09-18,previous scrape,Home in San Diego · ★4.81 · 3 bedrooms · 3 bed...,"You read that right, this craftsman home was t...","We have the best Neighborhood in San Diego, in...",https://a0.muscache.com/pictures/miso/Hosting-...,29,...,4.97,4.77,4.80,"STR-04545L, 631067",f,1,1,0,0,0.82
1,29967,https://www.airbnb.com/rooms/29967,20230918050343,2023-09-18,city scrape,Bungalow in San Diego · ★4.77 · 2 bedrooms · 3...,"This 2 bedroom, 2 full bathroom home offers al...",NaN,https://a0.muscache.com/pictures/76103867/c9b5...,129123,...,4.92,4.81,4.76,"STR-05218L, 645110",f,5,5,0,0,0.63
2,54001,https://www.airbnb.com/rooms/54001,20230918050343,2023-09-18,city scrape,Guesthouse in La Jolla · ★4.94 · 2 bedrooms · ...,"Off the beaten path: 4 garden areas, 2 garde...","Tranquility, stately trees, meditative, zen-fu...",https://a0.muscache.com/pictures/miso/Hosting-...,252692,...,4.97,4.97,4.89,"STR-05706L, 523003",f,1,1,0,0,2.04
3,62274,https://www.airbnb.com/rooms/62274,20230918050343,2023-09-18,city scrape,Guesthouse in San Diego · ★4.77 · 1 bedroom · ...,"Modern, cozy, artsy, and european in a lush ga...","We are in walking distance to Starbucks, Trade...",https://a0.muscache.com/pictures/84577734/93ca...,302986,...,4.86,4.87,4.79,"STR-00821L, 520121",f,3,2,1,0,5.31
4,75668,https://www.airbnb.com/rooms/75668,20230918050343,2023-09-18,city scrape,Condo in San Diego · ★4.83 · 1 bedroom · 1 bed...,<b>The space</b><br />Medium large bedroom wit...,NaN,https://a0.muscache.com/pictures/555077/d489e7...,401936,...,4.89,4.80,4.87,NaN,f,2,0,2,0,1.34

In [8]:
df['host_is_superhost'].describe()

count     12055
unique        2
top           f
freq       6647
Name: host_is_superhost, dtype: object

In [6]:
df['property_type'].value_counts()

property_type
Entire home                         4029
Entire rental unit                  2565
Entire condo                        1693
Private room in home                 936
Entire guesthouse                    584
                                    ...
Entire home/apt                        1
Yurt                                   1
Shared room in bed and breakfast       1
Tent                                   1
Cave                                   1
Name: count, Length: 61, dtype: int64

In [13]:
df['host_is_superhost'].value_counts()

host_is_superhost
f    6647
t    5408
Name: count, dtype: int64

In [12]:
df['host_listings_count'].value_counts()

host_listings_count
1.0     3386
2.0     1629
3.0      914
4.0      655
5.0      453
        ...
52.0       1
27.0       1
53.0       1
86.0       1
91.0       1
Name: count, Length: 114, dtype: int64

In [15]:
df['host_listings_count'].isna().sum()

3

In [9]:
df['property_type'].unique()

array(['Entire home', 'Entire bungalow', 'Entire guesthouse',
       'Private room in condo', 'Entire guest suite',
       'Entire bed and breakfast', 'Entire townhouse',
       'Private room in townhouse', 'Private room in home',
       'Entire rental unit', 'Tiny home', 'Entire condo',
       'Private room in rental unit', 'Entire cottage',
       'Private room in cottage', 'Private room in treehouse',
       'Treehouse', 'Earthen home', 'Entire loft',
       'Shared room in hostel', 'Entire cabin',
       'Private room in bungalow', 'Entire villa', 'Room in hotel',
       'Entire place', 'Entire serviced apartment',
       'Private room in hostel', 'Private room in guesthouse',
       'Private room', 'Camper/RV', 'Shared room in rental unit',
       'Room in boutique hotel', 'Private room in bed and breakfast',
       'Entire vacation home', 'Private room in guest suite',
       'Shared room in condo', 'Private room in camper/rv',
       'Private room in villa', 'Entire resort', 'Room in aparthotel',
       'Tent', 'Private room in resort', 'Private room in tiny home',
       'Private room in cave', 'Private room in hut',
       'Shared room in home', 'Private room in boat',
       'Private room in tent', 'Shared room in bungalow', 'Farm stay',
       'Barn', 'Private room in serviced apartment',
       'Private room in casa particular', 'Private room in vacation home',
       'Boat', 'Casa particular', 'Entire home/apt', 'Yurt',
       'Shared room in bed and breakfast', 'Campsite', 'Cave'],
      dtype=object)

In [4]:
df['room_type'].value_counts()

room_type
Entire home/apt    10562
Private room        1860
Shared room           72
Hotel room             3
Name: count, dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12497 entries, 0 to 12496
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            12497 non-null  int64
 1   listing_url                                   12497 non-null  object
 2   scrape_id                                     12497 non-null  int64
 3   last_scraped                                  12497 non-null  object
 4   source                                        12497 non-null  object
 5   name                                          12497 non-null  object
 6   description                                   12456 non-null  object
 7   neighborhood_overview                         8586 non-null   object
 8   picture_url                                   12497 non-null  object
 9   host_id                                       12497 non-null  int64
 10  host_url                                      12497 non-null  object
 11  host_name                                     12494 non-null  object
 12  host_since                                    12494 non-null  object
 13  host_location                                 10042 non-null  object
 14  host_about                                    8082 non-null   object
 15  host_response_time                            11245 non-null  object
 16  host_response_rate                            11245 non-null  object
 17  host_acceptance_rate                          11688 non-null  object
 18  host_is_superhost                             12055 non-null  object
 19  host_thumbnail_url                            12494 non-null  object
 20  host_picture_url                              12494 non-null  object
 21  host_neighbourhood                            11796 non-null  object
 22  host_listings_count                           12494 non-null  float64
 23  host_total_listings_count                     12494 non-null  float64
 24  host_verifications                            12497 non-null  object
 25  host_has_profile_pic                          12494 non-null  object
 26  host_identity_verified                        12494 non-null  object
 27  neighbourhood                                 8586 non-null   object
 28  neighbourhood_cleansed                        12497 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      12497 non-null  float64
 31  longitude                                     12497 non-null  float64
 32  property_type                                 12497 non-null  object
 33  room_type                                     12497 non-null  object
 34  accommodates                                  12497 non-null  int64
 35  bathrooms                                     0 non-null      float64
 36  bathrooms_text                                12494 non-null  object
 37  bedrooms                                      9996 non-null   float64
 38  beds                                          12361 non-null  float64
 39  amenities                                     12497 non-null  object
 40  price                                         12497 non-null  object
 41  minimum_nights                                12497 non-null  int64
 42  maximum_nights                                12497 non-null  int64
 43  minimum_minimum_nights                        12497 non-null  int64
 44  maximum_minimum_nights                        12497 non-null  int64
 45  minimum_maximum_nights                        12497 non-null  int64
 46  maximum_maximum_nights                        12497 non-null  int64
 47  minimum_nights_avg_ntm                        12497 non-null  float64
 48  maximum_nights_avg_ntm                        12497 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              12497 non-null  object
 51  availability_30                               12497 non-null  int64
 52  availability_60                               12497 non-null  int64
 53  availability_90                               12497 non-null  int64
 54  availability_365                              12497 non-null  int64
 55  calendar_last_scraped                         12497 non-null  object
 56  number_of_reviews                             12497 non-null  int64
 57  number_of_reviews_ltm                         12497 non-null  int64
 58  number_of_reviews_l30d                        12497 non-null  int64
 59  first_review                                  10657 non-null  object
 60  last_review                                   10657 non-null  object
 61  review_scores_rating                          10658 non-null  float64
 62  review_scores_accuracy                        10646 non-null  float64
 63  review_scores_cleanliness                     10646 non-null  float64
 64  review_scores_checkin                         10646 non-null  float64
 65  review_scores_communication                   10646 non-null  float64
 66  review_scores_location                        10646 non-null  float64
 67  review_scores_value                           10646 non-null  float64
 68  license                                       9453 non-null   object
 69  instant_bookable                              12497 non-null  object
 70  calculated_host_listings_count                12497 non-null  int64
 71  calculated_host_listings_count_entire_homes   12497 non-null  int64
 72  calculated_host_listings_count_private_rooms  12497 non-null  int64
 73  calculated_host_listings_count_shared_rooms   12497 non-null  int64
 74  reviews_per_month                             10657 non-null  float64
dtypes: float64(19), int64(21), object(35)
memory usage: 7.2+ MB

In [5]:
df['calendar_last_scraped'].value_counts()

2023-09-18    12497
Name: calendar_last_scraped, dtype: int64

In [6]:
df['neighbourhood'].value_counts()

San Diego, California, United States             8179
Chula Vista, California, United States            230
La Jolla, California, United States                73
Del Mar, California, United States                 50
National City, California, United States            5
La Mesa, California, United States                  4
Escondido, California, United States                3
Bonita, California, United States                   3
La Jolla , California, United States                3
Point Loma, California, United States               3
Solana Beach, California, United States             2
Tijuana, Baja California, Mexico                    2
San Diego , Ca, United States                       2
San Diego County, California, United States         2
Ocean Beach, California, United States              2
CA, United States                                   2
San Diego , California, United States               2
Mission Beach, California, United States            2
Del Mar Highlands , California, United States       1
 San Diego, California, United States               1
 La Jolla, California, United States                1
Imperial Beach, California, United States           1
LA JOLLA, CALIFORNIA, United States                 1
California, South Dakota, United States             1
SAN DIEGO, California, United States                1
La Jolla, San diego, United States                  1
San Diego, United States                            1
LA JOLLA, California, United States                 1
La Jolla Cove, California, United States            1
Coronado, California, United States                 1
San Diego, Ca, United States                        1
Gas lamp San Diego, California, United States       1
Lemon Grove, California, United States              1
Mission Bay, California, United States              1
San diego, California, United States                1
Name: neighbourhood, dtype: int64

In [7]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [8]:
df = df.drop(columns= ['scrape_id', 'source', 'host_acceptance_rate', 'host_thumbnail_url', 'host_picture_url' ,
                  'host_listings_count', 'host_has_profile_pic', 'neighbourhood_group_cleansed', 'bathrooms', 'calendar_updated',
                  'number_of_reviews_ltm', 'number_of_reviews_l30d', 'calendar_last_scraped', 'review_scores_accuracy', 
                  'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 
                  'review_scores_value', 'host_about', 'neighborhood_overview',
                   'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 
                   'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'license'])
df.head()

,id,listing_url,last_scraped,name,description,picture_url,host_id,host_url,host_name,host_since,...,number_of_reviews,first_review,last_review,review_scores_rating,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,6,https://www.airbnb.com/rooms/6,2023-09-18,Home in San Diego · ★4.81 · 3 bedrooms · 3 bed...,"You read that right, this craftsman home was t...",https://a0.muscache.com/pictures/miso/Hosting-...,29,https://www.airbnb.com/users/show/29,Sara,2008-03-03,...,153,2008-06-22,2019-09-14,4.81,f,1,1,0,0,0.82
1,29967,https://www.airbnb.com/rooms/29967,2023-09-18,Bungalow in San Diego · ★4.77 · 2 bedrooms · 3...,"This 2 bedroom, 2 full bathroom home offers al...",https://a0.muscache.com/pictures/76103867/c9b5...,129123,https://www.airbnb.com/users/show/129123,Michael,2010-05-21,...,102,2010-07-09,2023-08-25,4.77,f,5,5,0,0,0.63
2,54001,https://www.airbnb.com/rooms/54001,2023-09-18,Guesthouse in La Jolla · ★4.94 · 2 bedrooms · ...,"Off the beaten path: 4 garden areas, 2 garde...",https://a0.muscache.com/pictures/miso/Hosting-...,252692,https://www.airbnb.com/users/show/252692,Marsha,2010-10-04,...,316,2011-01-04,2023-09-01,4.94,f,1,1,0,0,2.04
3,62274,https://www.airbnb.com/rooms/62274,2023-09-18,Guesthouse in San Diego · ★4.77 · 1 bedroom · ...,"Modern, cozy, artsy, and european in a lush ga...",https://a0.muscache.com/pictures/84577734/93ca...,302986,https://www.airbnb.com/users/show/302986,Isabel,2010-11-28,...,826,2010-12-05,2023-09-03,4.77,f,3,2,1,0,5.31
4,75668,https://www.airbnb.com/rooms/75668,2023-09-18,Condo in San Diego · ★4.83 · 1 bedroom · 1 bed...,<b>The space</b><br />Medium large bedroom wit...,https://a0.muscache.com/pictures/555077/d489e7...,401936,https://www.airbnb.com/users/show/401936,Johnathon,2011-02-20,...,198,2011-07-25,2022-11-26,4.83,f,2,0,2,0,1.34

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12497 entries, 0 to 12496
Data columns (total 46 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            12497 non-null  int64
 1   listing_url                                   12497 non-null  object
 2   last_scraped                                  12497 non-null  object
 3   name                                          12497 non-null  object
 4   description                                   12456 non-null  object
 5   picture_url                                   12497 non-null  object
 6   host_id                                       12497 non-null  int64
 7   host_url                                      12497 non-null  object
 8   host_name                                     12494 non-null  object
 9   host_since                                    12494 non-null  object
 10  host_location                                 10042 non-null  object
 11  host_response_time                            11245 non-null  object
 12  host_response_rate                            11245 non-null  object
 13  host_neighbourhood                            11796 non-null  object
 14  host_total_listings_count                     12494 non-null  float64
 15  host_verifications                            12497 non-null  object
 16  host_identity_verified                        12494 non-null  object
 17  neighbourhood                                 8586 non-null   object
 18  neighbourhood_cleansed                        12497 non-null  object
 19  latitude                                      12497 non-null  float64
 20  longitude                                     12497 non-null  float64
 21  property_type                                 12497 non-null  object
 22  room_type                                     12497 non-null  object
 23  accommodates                                  12497 non-null  int64
 24  bathrooms_text                                12494 non-null  object
 25  bedrooms                                      9996 non-null   float64
 26  beds                                          12361 non-null  float64
 27  amenities                                     12497 non-null  object
 28  price                                         12497 non-null  object
 29  minimum_nights                                12497 non-null  int64
 30  maximum_nights                                12497 non-null  int64
 31  has_availability                              12497 non-null  object
 32  availability_30                               12497 non-null  int64
 33  availability_60                               12497 non-null  int64
 34  availability_90                               12497 non-null  int64
 35  availability_365                              12497 non-null  int64
 36  number_of_reviews                             12497 non-null  int64
 37  first_review                                  10657 non-null  object
 38  last_review                                   10657 non-null  object
 39  review_scores_rating                          10658 non-null  float64
 40  instant_bookable                              12497 non-null  object
 41  calculated_host_listings_count                12497 non-null  int64
 42  calculated_host_listings_count_entire_homes   12497 non-null  int64
 43  calculated_host_listings_count_private_rooms  12497 non-null  int64
 44  calculated_host_listings_count_shared_rooms   12497 non-null  int64
 45  reviews_per_month                             10657 non-null  float64
dtypes: float64(7), int64(14), object(25)
memory usage: 4.4+ MB

In [10]:
df.rename(columns={'last_scraped':'last_updated'}, inplace=True)

In [11]:
df['calculated_host_listings_count_shared_rooms'].value_counts()

0     12319
1        73
15       24
7        20
4        15
2        15
3        14
8        10
5         7
Name: calculated_host_listings_count_shared_rooms, dtype: int64

In [12]:
df.iloc[0, 3]

'Home in San Diego · ★4.81 · 3 bedrooms · 3 beds · 2 baths'

In [13]:
df.iloc[0, 4]

"You read that right, this craftsman home was the first full house EVER listed on Airbnb.  I have written out the full story in the house if you want to read it. Come stay in this beautiful home with a piece of history.  <br /><br />This Beautiful Craftsmen house has all the modern conveniences you enjoy with the craftsmen feel, in the heart of San Diego. <br /><br />Walking distance to all the local restaurants, bars, and breweries in the booming neighborhood of North Park. <br /><br />A perfect fit for families!<br /><br /><b>The space</b><br />The house is located in the heart of North Park.  It is the perfect location to be close to all the best attractions in San Diego as well as walking distance to North Park's incredible nightlife with hot new bars and restaurants.  The house is also only a couple minutes' drive from Balboa Park, the Zoo, and the gaslamp district Downtown where Comic Con is held.  During the day you can head to the beach or Sea World which are a short 10 min driv"

In [14]:
df['name'] = df['name'].str.split('·').str.get(0).str.strip()
df['description'] = df['description'].str.replace('<br />', '').str.replace('<b>', '').replace('</b>', '')

In [15]:
df.iloc[0, 4]

"You read that right, this craftsman home was the first full house EVER listed on Airbnb.  I have written out the full story in the house if you want to read it. Come stay in this beautiful home with a piece of history.  This Beautiful Craftsmen house has all the modern conveniences you enjoy with the craftsmen feel, in the heart of San Diego. Walking distance to all the local restaurants, bars, and breweries in the booming neighborhood of North Park. A perfect fit for families!The space</b>The house is located in the heart of North Park.  It is the perfect location to be close to all the best attractions in San Diego as well as walking distance to North Park's incredible nightlife with hot new bars and restaurants.  The house is also only a couple minutes' drive from Balboa Park, the Zoo, and the gaslamp district Downtown where Comic Con is held.  During the day you can head to the beach or Sea World which are a short 10 min driv"

In [16]:
df[['description','host_name', 'host_since', 'host_total_listings_count', 'host_identity_verified', 'host_location', 'host_response_time', 'host_response_rate', 'host_neighbourhood']] =  df[['description', 'host_name', 'host_since', 'host_total_listings_count', 'host_identity_verified', 'host_location', 'host_response_time', 'host_response_rate', 'host_neighbourhood']].fillna("unspecified")

In [17]:
import pandas as pd
with pd.option_context('display.max_rows', 15, 'display.max_columns', None):
    display(df)

,id,listing_url,last_updated,name,description,picture_url,host_id,host_url,host_name,host_since,host_location,host_response_time,host_response_rate,host_neighbourhood,host_total_listings_count,host_verifications,host_identity_verified,neighbourhood,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,first_review,last_review,review_scores_rating,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,6,https://www.airbnb.com/rooms/6,2023-09-18,Home in San Diego,"You read that right, this craftsman home was t...",https://a0.muscache.com/pictures/miso/Hosting-...,29,https://www.airbnb.com/users/show/29,Sara,2008-03-03,"San Diego, CA",unspecified,unspecified,North Park,1.0,"['email', 'phone']",t,"San Diego, California, United States",North Hills,32.755220,-117.128730,Entire home,Entire home/apt,6,2 baths,3.0,3.0,"[""Microwave"", ""Freezer"", ""Bathtub"", ""Central a...",$349.00,10,30,t,0,0,0,0,153,2008-06-22,2019-09-14,4.81,f,1,1,0,0,0.82
1,29967,https://www.airbnb.com/rooms/29967,2023-09-18,Bungalow in San Diego,"This 2 bedroom, 2 full bathroom home offers al...",https://a0.muscache.com/pictures/76103867/c9b5...,129123,https://www.airbnb.com/users/show/129123,Michael,2010-05-21,"San Diego, CA",within a few hours,100%,Pacific Beach,9.0,"['email', 'phone', 'work_email']",t,NaN,Pacific Beach,32.807510,-117.257600,Entire bungalow,Entire home/apt,6,2 baths,2.0,3.0,"[""Hangers"", ""Dryer"", ""Pack \u2019n play/Travel...",$225.00,4,365,t,14,14,18,286,102,2010-07-09,2023-08-25,4.77,f,5,5,0,0,0.63
2,54001,https://www.airbnb.com/rooms/54001,2023-09-18,Guesthouse in La Jolla,"Off the beaten path: 4 garden areas, 2 garde...",https://a0.muscache.com/pictures/miso/Hosting-...,252692,https://www.airbnb.com/users/show/252692,Marsha,2010-10-04,"San Diego, CA",within a few hours,100%,La Jolla,2.0,"['email', 'phone']",t,"La Jolla, California, United States",La Jolla,32.813010,-117.268560,Entire guesthouse,Entire home/apt,4,1 bath,2.0,3.0,"[""Clothing storage: closet and dresser"", ""Micr...",$147.00,4,365,t,0,3,26,99,316,2011-01-04,2023-09-01,4.94,f,1,1,0,0,2.04
3,62274,https://www.airbnb.com/rooms/62274,2023-09-18,Guesthouse in San Diego,"Modern, cozy, artsy, and european in a lush ga...",https://a0.muscache.com/pictures/84577734/93ca...,302986,https://www.airbnb.com/users/show/302986,Isabel,2010-11-28,"San Diego, CA",within an hour,100%,Pacific Beach,3.0,"['email', 'phone']",t,"San Diego, California, United States",Pacific Beach,32.805830,-117.242440,Entire guesthouse,Entire home/apt,2,1 bath,1.0,1.0,"[""Microwave"", ""Private patio or balcony"", ""Loc...",$89.00,2,14,t,1,5,22,273,826,2010-12-05,2023-09-03,4.77,f,3,2,1,0,5.31
4,75668,https://www.airbnb.com/rooms/75668,2023-09-18,Condo in San Diego,The space</b>Medium large bedroom with a queen...,https://a0.muscache.com/pictures/555077/d489e7...,401936,https://www.airbnb.com/users/show/401936,Johnathon,2011-02-20,"San Diego, CA",a few days or more,0%,North Park,3.0,"['email', 'phone']",t,NaN,North Hills,32.746990,-117.142430,Private room in condo,Private room,2,1 private bath,NaN,1.0,"[""Microwave"", ""Dryer"", ""Stove"", ""Patio or balc...",$45.00,31,1825,t,0,0,0,103,198,2011-07-25,2022-11-26,4.83,f,2,0,2,0,1.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12492,975626784766085577,https://www.airbnb.com/rooms/975626784766085577,2023-09-18,Rental unit in San Diego,Welcome to our centrally located place in the ...,https://a0.muscache.com/pictures/miso/Hosting-...,456697664,https://www.airbnb.com/users/show/456697664,Aarti,2022-04-29,"San Diego, CA",within an hour,100%,Birdland,155.0,"['email', 'phone']",t,NaN,Old Town,32.748330,-117.193440,Entire rental unit,Entire home/apt,3,1 bath,1.0,1.0,"[""Air conditioning"", ""Wifi"", ""Paid parking on ...",$108.00,1,365,t,4,4,13,15,0,NaN,NaN,NaN,t,76,76,0,0,NaN
12493,975645593399245481,https://www.airbnb.com/rooms/975645593399245481,2023-09-18,Home in San Diego,"This special place is close to everything, mak...",https://a0.muscache.com/pictures/a851c04a-0224...,20373580,https://www.airbnb.com/users/show/20373580,Celine,2014-08-21,"San Diego, CA",within an hour,100%,Serra Mesa,6.0,"['email', 'phone']",t,NaN,Serra Mesa,32.783384,-117.151287,Entire home,Entire home/apt,10,2.5 baths,4.0,4.0,"[""Microwave"", ""Freezer"", ""Bathtub"", ""Dryer"", ""...",$476.00,1,365,t,22,22,22,22,0,NaN,NaN,NaN,f,2,2,0,0,NaN
12494,975905015986457757,https://www.airbnb.com/rooms/975905015986457757,2023-09-18,Home in San Diego,Forget your worries in this spacious and seren...,https://a0.muscache.com/pictures/miso/Hosting-...,46637397,https://www.airbnb.com/users/show/46637397,Ken,2015-10-15,"San Diego, CA",within an hour,100%,Del Cerro,14.0,"['email', 'phone', 'work_email']",t,NaN,Wooded Area,32.719056,-117.253385,Private room in home,Private room,2,1 bath,NaN,1.0,"[""Dryer"", ""Free parking on premises"", ""Beach a...",$99.00,1,365,t,16,17,17,17,0,NaN,NaN,NaN,t,5,2,3,0,NaN
12495,976129491368742667,https://www.airbnb.com/rooms/976129491368742667,2023-09-18,Rental unit in San Diego,Enjoy a stylish experience at this centrally-l...,https://a0.muscache.com/pictures/miso/Hosting-...,280198638,https://www.airbnb.com/users/show/280198638,Travel And Luxury,2019-07-28,unspecified,within a day,92%,Downtown,14.0,"['email', 'phone']",t,NaN,East Village,32.707163,-117.154779,Entire rental unit,Entire home/apt,4,2 baths,2.0,2.0,"[""Pool"", ""Lockbox"", ""Air conditioning"", ""Hot t...",$410.00,1,365,t,28,58,88,88,0,NaN,NaN,NaN,f,3,3,0,0,NaN
12496,976138831185478864,https://www.airbnb.com/rooms/976138831185478864,2023-09-18,Home in San Diego,"Amazing 3BD + 1BD House in the Heart of PB, wi...",https://a0.muscache.com/pictures/prohost-api/H...,2772383,https://www.airbnb.com/users/show/2772383,San Diego,2012-06-28,"San Diego, CA",within an hour,98%,Mission Beach,74.0,"['email', 'phone', 'work_email']",t,NaN,Pacific Beach,32.802100,-117.245270,Entire home,Entire home/apt,10,4 baths,4.0,NaN,"[""Microwave"", ""Pool"", ""Bathtub"", ""Dryer"", ""Sto...",$551.00,3,365,t,26,53,79,324,0,NaN,NaN,NaN,t,47,47,0,0,NaN

In [18]:
df['neighbourhood_cleansed'].unique()

array(['North Hills', 'Pacific Beach', 'La Jolla', 'Old Town', 'Midtown',
       'North City', 'Bay Park', 'West University Heights', 'Ocean Beach',
       'Rolling Hills Ranch', 'Clairemont Mesa', 'Mira Mesa',
       'Mission Bay', 'Carmel Valley', 'Loma Portal', 'Moreno Mission',
       'Park West', 'Linda Vista', 'Balboa Park', 'South Park',
       'Cortez Hill', 'Normal Heights', 'Little Italy', 'East Village',
       'Rancho Penasquitos', 'Marina', 'Grantville', 'Roseville',
       'Mission Valley', 'Grant Hill', 'College Area', 'Serra Mesa',
       'Gaslamp Quarter', 'University City', 'Del Mar Heights',
       'Northwest', 'Kensington', 'Otay Ranch', 'Sabre Springs',
       'Columbia', 'North Clairemont', 'Bay Ho', 'Talmadge',
       'Valencia Park', 'Rancho Bernadino', 'El Cerritos', 'Kearny Mesa',
       'Memorial', 'Bario Logan', 'Southwest', 'Chollas View',
       'La Jolla Village', 'Encanto', 'Gateway', 'Scripps Ranch',
       'Wooded Area', 'Sky Line', 'Jomacha-Lomita', 'Mountain View',
       'Torrey Pines', 'Core', 'Rancho Del Rey', 'Mount Hope',
       'San Carlos', 'Paradise Hills', 'Amphitheater And Water Park',
       'Tierrasanta', 'Eastlake Vistas', 'Eastlake Woods',
       'City Heights East', 'Del Cerro', 'Bay Terrace', 'Oak Park',
       'Rolando', 'Paseo Ranchoero', 'San Ysidro', 'City Heights West',
       'Nestor', 'Sorrento Valley', 'Carmel Mountain', 'Midtown District',
       'Southcrest', 'Allied Gardens', 'Yosemite Dr', 'Sunbow',
       'Bonita Long Canyon', 'Lincoln Park', 'Webster', 'Lake Murray',
       'Darnall', 'Terra Nova', 'Alta Vista', 'East Lake', 'Bird Land',
       'Eastlake Trails', 'Emerald Hills', 'Egger Highlands',
       'Lynwood Hills', 'Horton Plaza', 'Estlake Greens',
       'Tijuana River Valley', 'Palm City'], dtype=object)

In [19]:
df['neighbourhood'].unique()

array(['San Diego, California, United States', nan,
       'La Jolla, California, United States',
       'Chula Vista, California, United States',
       'Del Mar, California, United States',
       'La Jolla, San diego, United States',
       'Ocean Beach, California, United States',
       'LA JOLLA, California, United States',
       'Lemon Grove, California, United States',
       'Mission Beach, California, United States',
       'Coronado, California, United States',
       'Solana Beach, California, United States',
       'Escondido, California, United States',
       'San Diego , California, United States',
       'La Jolla , California, United States',
       'La Mesa, California, United States',
       'Tijuana, Baja California, Mexico',
       'Del Mar Highlands , California, United States',
       'San diego, California, United States',
       'Mission Bay, California, United States',
       'Bonita, California, United States',
       'Gas lamp San Diego, California, United States',
       'San Diego, Ca, United States', 'CA, United States',
       'La Jolla Cove, California, United States',
       'San Diego County, California, United States',
       'San Diego, United States', 'San Diego , Ca, United States',
       'National City, California, United States',
       'SAN DIEGO, California, United States',
       'California, South Dakota, United States',
       'LA JOLLA, CALIFORNIA, United States',
       'Imperial Beach, California, United States',
       ' La Jolla, California, United States',
       ' San Diego, California, United States',
       'Point Loma, California, United States'], dtype=object)

In [20]:
neighbourhood_mapping = {
     'San Diego , California, United States' : 'San Diego, California, United States', 
     'San diego, California, United States' : 'San Diego, California, United States', 
     'San Diego, Ca, United States' : 'San Diego, California, United States', 
     'San Diego County, California, United States' : 'San Diego, California, United States', 
     'San Diego, United States' : 'San Diego, California, United States', 
     'San Diego , Ca, United States' : 'San Diego, California, United States', 
     ' San Diego, California, United States' : 'San Diego, California, United States', 
     'SAN DIEGO, California, United States' : 'San Diego, California, United States',
     'La Jolla, California, United States' : 'La Jolla, San diego, United States', 
     'LA JOLLA, California, United States' : 'La Jolla, San diego, United States', 
     'La Jolla , California, United States' :  'La Jolla, San diego, United States', 
     'Mission Bay, California, United States' :  'Mission Beach, California, United States',
     'La Jolla Cove, California, United States' : 'La Jolla, San diego, United States', 
     'LA JOLLA, CALIFORNIA, United States' : 'La Jolla, San diego, United States',
     ' La Jolla, California, United States': 'La Jolla, San diego, United States', 
     'CA, United States' : 'California, United States', 
     'California, South Dakota, United States' : 'California, United States'
}
df['neighbourhood'] = df['neighbourhood'].map(neighbourhood_mapping).fillna(df['neighbourhood'])
df['neighbourhood'] = df['neighbourhood'].fillna('San Diego, California, United States')

In [21]:
df['neighbourhood'].value_counts()

San Diego, California, United States             12101
Chula Vista, California, United States             230
La Jolla, San diego, United States                  81
Del Mar, California, United States                  50
National City, California, United States             5
La Mesa, California, United States                   4
California, United States                            3
Bonita, California, United States                    3
Escondido, California, United States                 3
Mission Beach, California, United States             3
Point Loma, California, United States                3
Solana Beach, California, United States              2
Tijuana, Baja California, Mexico                     2
Ocean Beach, California, United States               2
Coronado, California, United States                  1
Del Mar Highlands , California, United States        1
Gas lamp San Diego, California, United States        1
Lemon Grove, California, United States               1
Imperial Beach, California, United States            1
Name: neighbourhood, dtype: int64

In [22]:
df['neighbourhood_cleansed'].unique()

array(['North Hills', 'Pacific Beach', 'La Jolla', 'Old Town', 'Midtown',
       'North City', 'Bay Park', 'West University Heights', 'Ocean Beach',
       'Rolling Hills Ranch', 'Clairemont Mesa', 'Mira Mesa',
       'Mission Bay', 'Carmel Valley', 'Loma Portal', 'Moreno Mission',
       'Park West', 'Linda Vista', 'Balboa Park', 'South Park',
       'Cortez Hill', 'Normal Heights', 'Little Italy', 'East Village',
       'Rancho Penasquitos', 'Marina', 'Grantville', 'Roseville',
       'Mission Valley', 'Grant Hill', 'College Area', 'Serra Mesa',
       'Gaslamp Quarter', 'University City', 'Del Mar Heights',
       'Northwest', 'Kensington', 'Otay Ranch', 'Sabre Springs',
       'Columbia', 'North Clairemont', 'Bay Ho', 'Talmadge',
       'Valencia Park', 'Rancho Bernadino', 'El Cerritos', 'Kearny Mesa',
       'Memorial', 'Bario Logan', 'Southwest', 'Chollas View',
       'La Jolla Village', 'Encanto', 'Gateway', 'Scripps Ranch',
       'Wooded Area', 'Sky Line', 'Jomacha-Lomita', 'Mountain View',
       'Torrey Pines', 'Core', 'Rancho Del Rey', 'Mount Hope',
       'San Carlos', 'Paradise Hills', 'Amphitheater And Water Park',
       'Tierrasanta', 'Eastlake Vistas', 'Eastlake Woods',
       'City Heights East', 'Del Cerro', 'Bay Terrace', 'Oak Park',
       'Rolando', 'Paseo Ranchoero', 'San Ysidro', 'City Heights West',
       'Nestor', 'Sorrento Valley', 'Carmel Mountain', 'Midtown District',
       'Southcrest', 'Allied Gardens', 'Yosemite Dr', 'Sunbow',
       'Bonita Long Canyon', 'Lincoln Park', 'Webster', 'Lake Murray',
       'Darnall', 'Terra Nova', 'Alta Vista', 'East Lake', 'Bird Land',
       'Eastlake Trails', 'Emerald Hills', 'Egger Highlands',
       'Lynwood Hills', 'Horton Plaza', 'Estlake Greens',
       'Tijuana River Valley', 'Palm City'], dtype=object)

In [23]:
df.columns

Index(['id', 'listing_url', 'last_updated', 'name', 'description',
       'picture_url', 'host_id', 'host_url', 'host_name', 'host_since',
       'host_location', 'host_response_time', 'host_response_rate',
       'host_neighbourhood', 'host_total_listings_count', 'host_verifications',
       'host_identity_verified', 'neighbourhood', 'neighbourhood_cleansed',
       'latitude', 'longitude', 'property_type', 'room_type', 'accommodates',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'number_of_reviews', 'first_review', 'last_review',
       'review_scores_rating', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [24]:
list1 = ['id', 'listing_url', 'last_updated', 'name', 'description',
       'picture_url', 'host_id', 'host_url', 'host_name', 'host_since',
       'host_location', 'host_response_time', 'host_response_rate',
       'host_neighbourhood', 'host_total_listings_count', 'host_verifications',
       'host_identity_verified', 'neighbourhood', 'neighbourhood_cleansed',
       'latitude', 'longitude']
df1 = df[list1]
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12497 entries, 0 to 12496
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         12497 non-null  int64
 1   listing_url                12497 non-null  object
 2   last_updated               12497 non-null  object
 3   name                       12497 non-null  object
 4   description                12497 non-null  object
 5   picture_url                12497 non-null  object
 6   host_id                    12497 non-null  int64
 7   host_url                   12497 non-null  object
 8   host_name                  12497 non-null  object
 9   host_since                 12497 non-null  object
 10  host_location              12497 non-null  object
 11  host_response_time         12497 non-null  object
 12  host_response_rate         12497 non-null  object
 13  host_neighbourhood         12497 non-null  object
 14  host_total_listings_count  12497 non-null  object
 15  host_verifications         12497 non-null  object
 16  host_identity_verified     12497 non-null  object
 17  neighbourhood              12497 non-null  object
 18  neighbourhood_cleansed     12497 non-null  object
 19  latitude                   12497 non-null  float64
 20  longitude                  12497 non-null  float64
dtypes: float64(2), int64(2), object(17)
memory usage: 2.0+ MB

In [25]:
df['neighbourhood'].value_counts()

San Diego, California, United States             12101
Chula Vista, California, United States             230
La Jolla, San diego, United States                  81
Del Mar, California, United States                  50
National City, California, United States             5
La Mesa, California, United States                   4
California, United States                            3
Bonita, California, United States                    3
Escondido, California, United States                 3
Mission Beach, California, United States             3
Point Loma, California, United States                3
Solana Beach, California, United States              2
Tijuana, Baja California, Mexico                     2
Ocean Beach, California, United States               2
Coronado, California, United States                  1
Del Mar Highlands , California, United States        1
Gas lamp San Diego, California, United States        1
Lemon Grove, California, United States               1
Imperial Beach, California, United States            1
Name: neighbourhood, dtype: int64

In [26]:
mean_rating = df['review_scores_rating'].mean()
df['review_scores_rating'].fillna(mean_rating, inplace=True)

In [27]:
df['reviews_per_month'] = df['reviews_per_month'].fillna(0)
df['first_review'] = df['first_review'].fillna(0).apply(pd.to_datetime)
df['last_review'] = df['last_review'].fillna(0).apply(pd.to_datetime)
df[['bathrooms_text', 'bedrooms', 'beds']] = df[['bathrooms_text', 'bedrooms', 'beds']].fillna(0)

In [28]:
list2 = [ 'property_type', 'room_type', 'accommodates',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'number_of_reviews', 'first_review', 'last_review',
       'review_scores_rating', 'instant_bookable']
df2 = df[list2]
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12497 entries, 0 to 12496
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   property_type         12497 non-null  object
 1   room_type             12497 non-null  object
 2   accommodates          12497 non-null  int64
 3   bathrooms_text        12497 non-null  object
 4   bedrooms              12497 non-null  float64
 5   beds                  12497 non-null  float64
 6   amenities             12497 non-null  object
 7   price                 12497 non-null  object
 8   minimum_nights        12497 non-null  int64
 9   maximum_nights        12497 non-null  int64
 10  has_availability      12497 non-null  object
 11  availability_30       12497 non-null  int64
 12  availability_60       12497 non-null  int64
 13  availability_90       12497 non-null  int64
 14  availability_365      12497 non-null  int64
 15  number_of_reviews     12497 non-null  int64
 16  first_review          12497 non-null  datetime64[ns]
 17  last_review           12497 non-null  datetime64[ns]
 18  review_scores_rating  12497 non-null  float64
 19  instant_bookable      12497 non-null  object
dtypes: datetime64[ns](2), float64(3), int64(8), object(7)
memory usage: 1.9+ MB

In [29]:
list3 = [  'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month']
df3 = df[list3]
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12497 entries, 0 to 12496
Data columns (total 5 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   calculated_host_listings_count                12497 non-null  int64
 1   calculated_host_listings_count_entire_homes   12497 non-null  int64
 2   calculated_host_listings_count_private_rooms  12497 non-null  int64
 3   calculated_host_listings_count_shared_rooms   12497 non-null  int64
 4   reviews_per_month                             12497 non-null  float64
dtypes: float64(1), int64(4)
memory usage: 488.3 KB

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12497 entries, 0 to 12496
Data columns (total 46 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            12497 non-null  int64
 1   listing_url                                   12497 non-null  object
 2   last_updated                                  12497 non-null  object
 3   name                                          12497 non-null  object
 4   description                                   12497 non-null  object
 5   picture_url                                   12497 non-null  object
 6   host_id                                       12497 non-null  int64
 7   host_url                                      12497 non-null  object
 8   host_name                                     12497 non-null  object
 9   host_since                                    12497 non-null  object
 10  host_location                                 12497 non-null  object
 11  host_response_time                            12497 non-null  object
 12  host_response_rate                            12497 non-null  object
 13  host_neighbourhood                            12497 non-null  object
 14  host_total_listings_count                     12497 non-null  object
 15  host_verifications                            12497 non-null  object
 16  host_identity_verified                        12497 non-null  object
 17  neighbourhood                                 12497 non-null  object
 18  neighbourhood_cleansed                        12497 non-null  object
 19  latitude                                      12497 non-null  float64
 20  longitude                                     12497 non-null  float64
 21  property_type                                 12497 non-null  object
 22  room_type                                     12497 non-null  object
 23  accommodates                                  12497 non-null  int64
 24  bathrooms_text                                12497 non-null  object
 25  bedrooms                                      12497 non-null  float64
 26  beds                                          12497 non-null  float64
 27  amenities                                     12497 non-null  object
 28  price                                         12497 non-null  object
 29  minimum_nights                                12497 non-null  int64
 30  maximum_nights                                12497 non-null  int64
 31  has_availability                              12497 non-null  object
 32  availability_30                               12497 non-null  int64
 33  availability_60                               12497 non-null  int64
 34  availability_90                               12497 non-null  int64
 35  availability_365                              12497 non-null  int64
 36  number_of_reviews                             12497 non-null  int64
 37  first_review                                  12497 non-null  datetime64[ns]
 38  last_review                                   12497 non-null  datetime64[ns]
 39  review_scores_rating                          12497 non-null  float64
 40  instant_bookable                              12497 non-null  object
 41  calculated_host_listings_count                12497 non-null  int64
 42  calculated_host_listings_count_entire_homes   12497 non-null  int64
 43  calculated_host_listings_count_private_rooms  12497 non-null  int64
 44  calculated_host_listings_count_shared_rooms   12497 non-null  int64
 45  reviews_per_month                             12497 non-null  float64
dtypes: datetime64[ns](2), float64(6), int64(14), object(24)
memory usage: 4.4+ MB

In [31]:
df.isna().sum()

id                                              0
listing_url                                     0
last_updated                                    0
name                                            0
description                                     0
picture_url                                     0
host_id                                         0
host_url                                        0
host_name                                       0
host_since                                      0
host_location                                   0
host_response_time                              0
host_response_rate                              0
host_neighbourhood                              0
host_total_listings_count                       0
host_verifications                              0
host_identity_verified                          0
neighbourhood                                   0
neighbourhood_cleansed                          0
latitude                                        0
longitude                                       0
property_type                                   0
room_type                                       0
accommodates                                    0
bathrooms_text                                  0
bedrooms                                        0
beds                                            0
amenities                                       0
price                                           0
minimum_nights                                  0
maximum_nights                                  0
has_availability                                0
availability_30                                 0
availability_60                                 0
availability_90                                 0
availability_365                                0
number_of_reviews                               0
first_review                                    0
last_review                                     0
review_scores_rating                            0
instant_bookable                                0
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
dtype: int64

In [32]:
df = df.drop(columns=['host_verifications', 'property_type', 'availability_60', 'availability_90' ,'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms'])

In [33]:
df.rename(columns={'id':'listing_id', 'neighbourhood_cleansed': 'neighbourhood_view', 'room_type': 'property_type', 'bathrooms_text':'bathrooms'}, inplace=True)

In [34]:
with pd.option_context('display.max_rows', 15, 'display.max_columns', None):
    display(df)

,listing_id,listing_url,last_updated,name,description,picture_url,host_id,host_url,host_name,host_since,host_location,host_response_time,host_response_rate,host_neighbourhood,host_total_listings_count,host_identity_verified,neighbourhood,neighbourhood_view,latitude,longitude,property_type,accommodates,bathrooms,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,has_availability,availability_30,availability_365,number_of_reviews,first_review,last_review,review_scores_rating,instant_bookable,reviews_per_month
0,6,https://www.airbnb.com/rooms/6,2023-09-18,Home in San Diego,"You read that right, this craftsman home was t...",https://a0.muscache.com/pictures/miso/Hosting-...,29,https://www.airbnb.com/users/show/29,Sara,2008-03-03,"San Diego, CA",unspecified,unspecified,North Park,1.0,t,"San Diego, California, United States",North Hills,32.755220,-117.128730,Entire home/apt,6,2 baths,3.0,3.0,"[""Microwave"", ""Freezer"", ""Bathtub"", ""Central a...",$349.00,10,30,t,0,0,153,2008-06-22,2019-09-14,4.810000,f,0.82
1,29967,https://www.airbnb.com/rooms/29967,2023-09-18,Bungalow in San Diego,"This 2 bedroom, 2 full bathroom home offers al...",https://a0.muscache.com/pictures/76103867/c9b5...,129123,https://www.airbnb.com/users/show/129123,Michael,2010-05-21,"San Diego, CA",within a few hours,100%,Pacific Beach,9.0,t,"San Diego, California, United States",Pacific Beach,32.807510,-117.257600,Entire home/apt,6,2 baths,2.0,3.0,"[""Hangers"", ""Dryer"", ""Pack \u2019n play/Travel...",$225.00,4,365,t,14,286,102,2010-07-09,2023-08-25,4.770000,f,0.63
2,54001,https://www.airbnb.com/rooms/54001,2023-09-18,Guesthouse in La Jolla,"Off the beaten path: 4 garden areas, 2 garde...",https://a0.muscache.com/pictures/miso/Hosting-...,252692,https://www.airbnb.com/users/show/252692,Marsha,2010-10-04,"San Diego, CA",within a few hours,100%,La Jolla,2.0,t,"La Jolla, San diego, United States",La Jolla,32.813010,-117.268560,Entire home/apt,4,1 bath,2.0,3.0,"[""Clothing storage: closet and dresser"", ""Micr...",$147.00,4,365,t,0,99,316,2011-01-04,2023-09-01,4.940000,f,2.04
3,62274,https://www.airbnb.com/rooms/62274,2023-09-18,Guesthouse in San Diego,"Modern, cozy, artsy, and european in a lush ga...",https://a0.muscache.com/pictures/84577734/93ca...,302986,https://www.airbnb.com/users/show/302986,Isabel,2010-11-28,"San Diego, CA",within an hour,100%,Pacific Beach,3.0,t,"San Diego, California, United States",Pacific Beach,32.805830,-117.242440,Entire home/apt,2,1 bath,1.0,1.0,"[""Microwave"", ""Private patio or balcony"", ""Loc...",$89.00,2,14,t,1,273,826,2010-12-05,2023-09-03,4.770000,f,5.31
4,75668,https://www.airbnb.com/rooms/75668,2023-09-18,Condo in San Diego,The space</b>Medium large bedroom with a queen...,https://a0.muscache.com/pictures/555077/d489e7...,401936,https://www.airbnb.com/users/show/401936,Johnathon,2011-02-20,"San Diego, CA",a few days or more,0%,North Park,3.0,t,"San Diego, California, United States",North Hills,32.746990,-117.142430,Private room,2,1 private bath,0.0,1.0,"[""Microwave"", ""Dryer"", ""Stove"", ""Patio or balc...",$45.00,31,1825,t,0,103,198,2011-07-25,2022-11-26,4.830000,f,1.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12492,975626784766085577,https://www.airbnb.com/rooms/975626784766085577,2023-09-18,Rental unit in San Diego,Welcome to our centrally located place in the ...,https://a0.muscache.com/pictures/miso/Hosting-...,456697664,https://www.airbnb.com/users/show/456697664,Aarti,2022-04-29,"San Diego, CA",within an hour,100%,Birdland,155.0,t,"San Diego, California, United States",Old Town,32.748330,-117.193440,Entire home/apt,3,1 bath,1.0,1.0,"[""Air conditioning"", ""Wifi"", ""Paid parking on ...",$108.00,1,365,t,4,15,0,1970-01-01,1970-01-01,4.777629,t,0.00
12493,975645593399245481,https://www.airbnb.com/rooms/975645593399245481,2023-09-18,Home in San Diego,"This special place is close to everything, mak...",https://a0.muscache.com/pictures/a851c04a-0224...,20373580,https://www.airbnb.com/users/show/20373580,Celine,2014-08-21,"San Diego, CA",within an hour,100%,Serra Mesa,6.0,t,"San Diego, California, United States",Serra Mesa,32.783384,-117.151287,Entire home/apt,10,2.5 baths,4.0,4.0,"[""Microwave"", ""Freezer"", ""Bathtub"", ""Dryer"", ""...",$476.00,1,365,t,22,22,0,1970-01-01,1970-01-01,4.777629,f,0.00
12494,975905015986457757,https://www.airbnb.com/rooms/975905015986457757,2023-09-18,Home in San Diego,Forget your worries in this spacious and seren...,https://a0.muscache.com/pictures/miso/Hosting-...,46637397,https://www.airbnb.com/users/show/46637397,Ken,2015-10-15,"San Diego, CA",within an hour,100%,Del Cerro,14.0,t,"San Diego, California, United States",Wooded Area,32.719056,-117.253385,Private room,2,1 bath,0.0,1.0,"[""Dryer"", ""Free parking on premises"", ""Beach a...",$99.00,1,365,t,16,17,0,1970-01-01,1970-01-01,4.777629,t,0.00
12495,976129491368742667,https://www.airbnb.com/rooms/976129491368742667,2023-09-18,Rental unit in San Diego,Enjoy a stylish experience at this centrally-l...,https://a0.muscache.com/pictures/miso/Hosting-...,280198638,https://www.airbnb.com/users/show/280198638,Travel And Luxury,2019-07-28,unspecified,within a day,92%,Downtown,14.0,t,"San Diego, California, United States",East Village,32.707163,-117.154779,Entire home/apt,4,2 baths,2.0,2.0,"[""Pool"", ""Lockbox"", ""Air conditioning"", ""Hot t...",$410.00,1,365,t,28,88,0,1970-01-01,1970-01-01,4.777629,f,0.00
12496,976138831185478864,https://www.airbnb.com/rooms/976138831185478864,2023-09-18,Home in San Diego,"Amazing 3BD + 1BD House in the Heart of PB, wi...",https://a0.muscache.com/pictures/prohost-api/H...,2772383,https://www.airbnb.com/users/show/2772383,San Diego,2012-06-28,"San Diego, CA",within an hour,98%,Mission Beach,74.0,t,"San Diego, California, United States",Pacific Beach,32.802100,-117.245270,Entire home/apt,10,4 baths,4.0,0.0,"[""Microwave"", ""Pool"", ""Bathtub"", ""Dryer"", ""Sto...",$551.00,3,365,t,26,324,0,1970-01-01,1970-01-01,4.777629,t,0.00

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12497 entries, 0 to 12496
Data columns (total 38 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   listing_id                 12497 non-null  int64
 1   listing_url                12497 non-null  object
 2   last_updated               12497 non-null  object
 3   name                       12497 non-null  object
 4   description                12497 non-null  object
 5   picture_url                12497 non-null  object
 6   host_id                    12497 non-null  int64
 7   host_url                   12497 non-null  object
 8   host_name                  12497 non-null  object
 9   host_since                 12497 non-null  object
 10  host_location              12497 non-null  object
 11  host_response_time         12497 non-null  object
 12  host_response_rate         12497 non-null  object
 13  host_neighbourhood         12497 non-null  object
 14  host_total_listings_count  12497 non-null  object
 15  host_identity_verified     12497 non-null  object
 16  neighbourhood              12497 non-null  object
 17  neighbourhood_view         12497 non-null  object
 18  latitude                   12497 non-null  float64
 19  longitude                  12497 non-null  float64
 20  property_type              12497 non-null  object
 21  accommodates               12497 non-null  int64
 22  bathrooms                  12497 non-null  object
 23  bedrooms                   12497 non-null  float64
 24  beds                       12497 non-null  float64
 25  amenities                  12497 non-null  object
 26  price                      12497 non-null  object
 27  minimum_nights             12497 non-null  int64
 28  maximum_nights             12497 non-null  int64
 29  has_availability           12497 non-null  object
 30  availability_30            12497 non-null  int64
 31  availability_365           12497 non-null  int64
 32  number_of_reviews          12497 non-null  int64
 33  first_review               12497 non-null  datetime64[ns]
 34  last_review                12497 non-null  datetime64[ns]
 35  review_scores_rating       12497 non-null  float64
 36  instant_bookable           12497 non-null  object
 37  reviews_per_month          12497 non-null  float64
dtypes: datetime64[ns](2), float64(6), int64(8), object(22)
memory usage: 3.6+ MB

In [20]:
from lookups import Sources, InputTypes
from database_handler import read_data_as_dataframe
df_2 = read_data_as_dataframe(InputTypes.CSV, 'csv_files\\reviews.csv')
df_2

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,6,8,2008-06-22,415,Terrence,Sara is an awesome hostess. She was very cons...
1,6,4383,2009-06-22,3762,Christine,My stay at “Craftsmen” was wonderful! Sara wa...
2,6,1722383,2012-07-16,1864778,Hieu,This was my first time using Airbnb and Sara m...
3,6,5595071,2013-07-07,117966,Maria,Sara was a very pleasant host! Reservation was...
4,6,5631156,2013-07-08,6563815,Mathew,Sara was such an amazing hostess! My girlfrien...
...,...,...,...,...,...,...
760802,972756225145030863,980519193155992083,2023-09-14,100393257,Maria C,"The place was in a great location , easy to tr..."
760803,972841948082325213,975504783915668190,2023-09-07,215905022,Kamielea,I had a lot of fun staying at this Airbnb. Ale...
760804,972841948082325213,976174894758092447,2023-09-08,231329188,S,What a delightful space to enjoy! We came as a...
760805,973108526049311119,978404137437934537,2023-09-11,506879501,Chani,Very clean and the host had great communicatio...
760806,973285217121157648,982748425442699644,2023-09-17,508950257,Esrom,Good location and price. Able to reach all the...

In [22]:
df_2['listing_id'].nunique()

10657

In [11]:
df_2['date'].describe()

count         760807
unique          4297
top       2023-05-29
freq            1573
Name: date, dtype: object

In [3]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760807 entries, 0 to 760806
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   listing_id     760807 non-null  int64
 1   id             760807 non-null  int64
 2   date           760807 non-null  object
 3   reviewer_id    760807 non-null  int64
 4   reviewer_name  760807 non-null  object
 5   comments       760634 non-null  object
dtypes: int64(3), object(3)
memory usage: 34.8+ MB

In [4]:
df_2['comments'].fillna('unspecified')

0         Sara is an awesome hostess.  She was very cons...
1         My stay at “Craftsmen” was wonderful!  Sara wa...
2         This was my first time using Airbnb and Sara m...
3         Sara was a very pleasant host! Reservation was...
4         Sara was such an amazing hostess! My girlfrien...
                                ...
760802    The place was in a great location , easy to tr...
760803    I had a lot of fun staying at this Airbnb. Ale...
760804    What a delightful space to enjoy! We came as a...
760805    Very clean and the host had great communicatio...
760806    Good location and price. Able to reach all the...
Name: comments, Length: 760807, dtype: object

In [5]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
df_2

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,6,8,2008-06-22,415,Terrence,"Sara is an awesome hostess. She was very considerate, making me feel right at home. Her suggestions of local well-known and up-and-coming hotspots were also very helpful. Definitely a positive experience. Her dog is a sweetie too!"
1,6,4383,2009-06-22,3762,Christine,"My stay at “Craftsmen” was wonderful! Sara was a lovely hostess, has a cute and stylish home, and her dog is super adorable. She is not kidding, it’s the most comfortable futon ever! Sara was thoughtful, caring, fun to be around, and a very cool gal. I wasn't expecting such hospitality, but she truly took care of me while I was there, helping me have a very memorable experience in San Diego. If you are thinking of going to Cali, you must go to San Diego, and Sara's is the place to be! It is very close to the fabulous San Diego Zoo and beautiful Balboa Park, and a short trip to downtown, Coronado Island or the coast. I hope I have the opportunity to visit “Craftsmen” again. Thanks Sara :-)"
2,6,1722383,2012-07-16,1864778,Hieu,This was my first time using Airbnb and Sara made my trip super comfortable. The room and bathroom were very clean. She was very accommodating. The best part was she offered food and drinks during my stay. I would definitely book this place again.\r<br/>\r<br/>Thanks again Sara!
3,6,5595071,2013-07-07,117966,Maria,"Sara was a very pleasant host! Reservation was made in a very short notice and she was very flexible and responsive. <br/>The room we stayed in was clean, had a very comfortable bed, new wood floors & paint. Bathroom has been just renovated as well.<br/>The house is in a quite area so your sleep won't be interrupted by any outside notice. Plenty of parking spots close by. <br/>Their is also a nice entrance right from the room to a private patio where you can enjoy morning coffee or glass of wine in the evening. <br/>Good location - Zoo is 10 minutes away by car, close to the highways. <br/>Overall, great experience - awesome host, cosy place. Recommended!<br/>"
4,6,5631156,2013-07-08,6563815,Mathew,Sara was such an amazing hostess! My girlfriend and I stayed only one night but felt welcome as soon as we walked through the door. Our room was of high end hotel quality with all the comforts of home. Highly recommended!
...,...,...,...,...,...,...
760802,972756225145030863,980519193155992083,2023-09-14,100393257,Maria C,"The place was in a great location , easy to travel to all the main sites . It was clean and spacious . Great backyard . Will definitely stay here again !"
760803,972841948082325213,975504783915668190,2023-09-07,215905022,Kamielea,"I had a lot of fun staying at this Airbnb. Alexander was very nice and responsive. This place is super cute and I’ve never stayed at a Airbnb like this. I went with a group of friends, so we thought having the arcade games would be fun for the guys and the girls could hang out together upstairs (but I think the girls ended up playing more than the guys lol). The place is more near the stadium side of downtown. Honestly, I was a little worried about the area when we were driving in, but it turned out to not be a big deal. We felt safe. We had a parking spot inside of the garage and there are two coded doors to get in from the outside but you can come in more privately through the garage side too. The place was really cute, you can tell whoever designed it wanted the people to have fun when they were there which we definitely did."
760804,972841948082325213,976174894758092447,2023-09-08,231329188,S,"What a delightful space to enjoy! We came as a family to take advantage of all the fun things to do in San Diego, and this gem of a stay was everything we could have hoped for! The amenities provided in the unit were appreciated by the kids and adults! The arcade set up downstairs made it an easy spot to hang out. I don’t know who enjoyed it most-the kids enjoyed or my husband. The private bedrooms were relaxing and well equipped. The size of kitchen originally was a concern when booking, but it was well stocked! Between the rice cooker and air fryer we were able to cook most of our meals easily. We all enjoyed the stylish vibe and can’t wait to come again!"
760805,973108526049311119,978404137437934537,2023-09-11,506879501,Chani,Very clean and the host had great communication. I would definitely r stay again
760806,973285217121157648,982748425442699644,2023-09-17,508950257,Esrom,Good location and price. Able to reach all the good areas with ease.

In [11]:
from lookups import Sources, InputTypes
from database_handler import read_data_as_dataframe
# df_3 = read_data_as_dataframe(InputTypes.CSV, Sources.calender_source.value)
df_3 = read_data_as_dataframe(InputTypes.CSV, 'csv_files\\calendar.csv')
df_3

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,6,2023-09-18,f,$349.00,$349.00,10,30
1,6,2023-09-19,f,$349.00,$349.00,10,30
2,6,2023-09-20,f,$349.00,$349.00,10,30
3,6,2023-09-21,f,$349.00,$349.00,10,30
4,6,2023-09-22,f,$349.00,$349.00,10,30
...,...,...,...,...,...,...,...
4561400,982795166361022129,2024-09-12,f,$195.00,$195.00,2,365
4561401,982795166361022129,2024-09-13,f,$249.00,$249.00,2,365
4561402,982795166361022129,2024-09-14,f,$249.00,$249.00,2,365
4561403,982795166361022129,2024-09-15,f,$195.00,$195.00,2,365
4561404,982795166361022129,2024-09-16,f,$195.00,$195.00,2,365

In [23]:
df_3['listing_id'].nunique()

12497

In [12]:
df_3.loc[df_3['price'] != df_3['adjusted_price'], :]

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
4380,132966,2023-09-18,f,$80.00,$72.00,31,1120
4381,132966,2023-09-19,f,$80.00,$72.00,31,1120
4382,132966,2023-09-20,f,$80.00,$72.00,31,1120
4383,132966,2023-09-21,f,$80.00,$72.00,31,1120
4384,132966,2023-09-22,f,$80.00,$72.00,31,1120
...,...,...,...,...,...,...,...
4561035,982605464258940494,2024-09-12,t,$736.00,$714.00,3,365
4561036,982605464258940494,2024-09-13,t,"$1,065.00","$1,033.00",3,365
4561037,982605464258940494,2024-09-14,t,"$1,056.00","$1,024.00",3,365
4561038,982605464258940494,2024-09-15,t,$732.00,$710.00,3,365
4561039,982605464258940494,2024-09-16,f,$658.00,$638.00,3,365

In [13]:
df_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4561405 entries, 0 to 4561404
Data columns (total 7 columns):
 #   Column          Dtype
---  ------          -----
 0   listing_id      int64
 1   date            object
 2   available       object
 3   price           object
 4   adjusted_price  object
 5   minimum_nights  int64
 6   maximum_nights  int64
dtypes: int64(3), object(4)
memory usage: 243.6+ MB

In [14]:
import pandas as pd 
df_3.rename(columns={'date' : 'last_updated'}, inplace=True)
df_3['last_updated'] = df_3['last_updated'].apply(pd.to_datetime)

In [16]:
df_3['listing_id'] = df_3['listing_id'].astype('object')

In [17]:
df_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4561405 entries, 0 to 4561404
Data columns (total 7 columns):
 #   Column          Dtype
---  ------          -----
 0   listing_id      object
 1   last_updated    datetime64[ns]
 2   available       object
 3   price           object
 4   adjusted_price  object
 5   minimum_nights  int64
 6   maximum_nights  int64
dtypes: datetime64[ns](1), int64(2), object(4)
memory usage: 243.6+ MB

In [12]:
df_3['listing_id'].isna().sum()

0

In [40]:
df_3['date'].value_counts()

2023-09-18    12497
2024-05-26    12497
2024-05-24    12497
2024-05-23    12497
2024-05-22    12497
              ...
2024-01-16    12497
2024-01-15    12497
2024-01-14    12497
2024-01-13    12497
2024-09-16    12497
Name: date, Length: 365, dtype: int64

In [41]:
df_3['available'].value_counts()

t    2445696
f    2115709
Name: available, dtype: int64

In [26]:
common_listings_df = pd.merge(df_2, df_3, on='listing_id', how='inner')
common_listings_count = len(common_listings_df)
print(f'The number of common listing IDs is: {common_listings_count}')

MemoryError: Unable to allocate 2.07 GiB for an array with shape (277694555,) and data type int64

In [1]:
from pandas_handler import dataframes_cleansed
df66 = dataframes_cleansed()

In [1]:
from pandas_handler import dataframes_cleansed
dict = dataframes_cleansed()

In [2]:
for key in dict:
    value = dict[key]
    # print(f'Key: {key}, Value: {value}')

In [3]:
value = dict['cleaned_df1']
value

,listing_id,listing_url,last_updated,name,description,picture_url,host_id,host_url,host_name,host_since,...,maximum_nights,has_availability,availability_30,availability_365,number_of_reviews,first_review,last_review,review_scores_rating,instant_bookable,reviews_per_month
0,6,https://www.airbnb.com/rooms/6,2023-09-18,Home in San Diego,"You read that right, this craftsman home was t...",https://a0.muscache.com/pictures/miso/Hosting-...,29,https://www.airbnb.com/users/show/29,Sara,2008-03-03,...,30,t,0,0,153,2008-06-22,2019-09-14,4.810000,f,0.82
1,29967,https://www.airbnb.com/rooms/29967,2023-09-18,Bungalow in San Diego,"This 2 bedroom, 2 full bathroom home offers al...",https://a0.muscache.com/pictures/76103867/c9b5...,129123,https://www.airbnb.com/users/show/129123,Michael,2010-05-21,...,365,t,14,286,102,2010-07-09,2023-08-25,4.770000,f,0.63
2,54001,https://www.airbnb.com/rooms/54001,2023-09-18,Guesthouse in La Jolla,"Off the beaten path: 4 garden areas, 2 garde...",https://a0.muscache.com/pictures/miso/Hosting-...,252692,https://www.airbnb.com/users/show/252692,Marsha,2010-10-04,...,365,t,0,99,316,2011-01-04,2023-09-01,4.940000,f,2.04
3,62274,https://www.airbnb.com/rooms/62274,2023-09-18,Guesthouse in San Diego,"Modern, cozy, artsy, and european in a lush ga...",https://a0.muscache.com/pictures/84577734/93ca...,302986,https://www.airbnb.com/users/show/302986,Isabel,2010-11-28,...,14,t,1,273,826,2010-12-05,2023-09-03,4.770000,f,5.31
4,75668,https://www.airbnb.com/rooms/75668,2023-09-18,Condo in San Diego,The space</b>Medium large bedroom with a queen...,https://a0.muscache.com/pictures/555077/d489e7...,401936,https://www.airbnb.com/users/show/401936,Johnathon,2011-02-20,...,1825,t,0,103,198,2011-07-25,2022-11-26,4.830000,f,1.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12492,975626784766085577,https://www.airbnb.com/rooms/975626784766085577,2023-09-18,Rental unit in San Diego,Welcome to our centrally located place in the ...,https://a0.muscache.com/pictures/miso/Hosting-...,456697664,https://www.airbnb.com/users/show/456697664,Aarti,2022-04-29,...,365,t,4,15,0,1970-01-01,1970-01-01,4.777629,t,0.00
12493,975645593399245481,https://www.airbnb.com/rooms/975645593399245481,2023-09-18,Home in San Diego,"This special place is close to everything, mak...",https://a0.muscache.com/pictures/a851c04a-0224...,20373580,https://www.airbnb.com/users/show/20373580,Celine,2014-08-21,...,365,t,22,22,0,1970-01-01,1970-01-01,4.777629,f,0.00
12494,975905015986457757,https://www.airbnb.com/rooms/975905015986457757,2023-09-18,Home in San Diego,Forget your worries in this spacious and seren...,https://a0.muscache.com/pictures/miso/Hosting-...,46637397,https://www.airbnb.com/users/show/46637397,Ken,2015-10-15,...,365,t,16,17,0,1970-01-01,1970-01-01,4.777629,t,0.00
12495,976129491368742667,https://www.airbnb.com/rooms/976129491368742667,2023-09-18,Rental unit in San Diego,Enjoy a stylish experience at this centrally-l...,https://a0.muscache.com/pictures/miso/Hosting-...,280198638,https://www.airbnb.com/users/show/280198638,Travel And Luxury,2019-07-28,...,365,t,28,88,0,1970-01-01,1970-01-01,4.777629,f,0.00
12496,976138831185478864,https://www.airbnb.com/rooms/976138831185478864,2023-09-18,Home in San Diego,"Amazing 3BD + 1BD House in the Heart of PB, wi...",https://a0.muscache.com/pictures/prohost-api/H...,2772383,https://www.airbnb.com/users/show/2772383,San Diego,2012-06-28,...,365,t,26,324,0,1970-01-01,1970-01-01,4.777629,t,0.00

In [4]:
value.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12497 entries, 0 to 12496
Data columns (total 38 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   listing_id                 12497 non-null  object
 1   listing_url                12497 non-null  object
 2   last_updated               12497 non-null  object
 3   name                       12497 non-null  object
 4   description                12497 non-null  object
 5   picture_url                12497 non-null  object
 6   host_id                    12497 non-null  int64
 7   host_url                   12497 non-null  object
 8   host_name                  12497 non-null  object
 9   host_since                 12497 non-null  object
 10  host_location              12497 non-null  object
 11  host_response_time         12497 non-null  object
 12  host_response_rate         12497 non-null  object
 13  host_neighbourhood         12497 non-null  object
 14  host_total_listings_count  12497 non-null  object
 15  host_identity_verified     12497 non-null  object
 16  neighbourhood              12497 non-null  object
 17  neighbourhood_view         12497 non-null  object
 18  latitude                   12497 non-null  float64
 19  longitude                  12497 non-null  float64
 20  property_type              12497 non-null  object
 21  accommodates               12497 non-null  int64
 22  bathrooms                  12497 non-null  object
 23  bedrooms                   12497 non-null  float64
 24  beds                       12497 non-null  float64
 25  amenities                  12497 non-null  object
 26  price                      12497 non-null  object
 27  minimum_nights             12497 non-null  int64
 28  maximum_nights             12497 non-null  int64
 29  has_availability           12497 non-null  object
 30  availability_30            12497 non-null  int64
 31  availability_365           12497 non-null  int64
 32  number_of_reviews          12497 non-null  int64
 33  first_review               12497 non-null  datetime64[ns]
 34  last_review                12497 non-null  datetime64[ns]
 35  review_scores_rating       12497 non-null  float64
 36  instant_bookable           12497 non-null  object
 37  reviews_per_month          12497 non-null  float64
dtypes: datetime64[ns](2), float64(6), int64(7), object(23)
memory usage: 3.6+ MB

In [5]:
value2 = dict['cleaned_df2']
value2

,listing_id,id,last_updated,reviewer_id,reviewer_name,comments
0,6,8,2008-06-22,415,Terrence,Sara is an awesome hostess. She was very cons...
1,6,4383,2009-06-22,3762,Christine,My stay at “Craftsmen” was wonderful! Sara wa...
2,6,1722383,2012-07-16,1864778,Hieu,This was my first time using Airbnb and Sara m...
3,6,5595071,2013-07-07,117966,Maria,Sara was a very pleasant host! Reservation was...
4,6,5631156,2013-07-08,6563815,Mathew,Sara was such an amazing hostess! My girlfrien...
...,...,...,...,...,...,...
760802,972756225145030863,980519193155992083,2023-09-14,100393257,Maria C,"The place was in a great location , easy to tr..."
760803,972841948082325213,975504783915668190,2023-09-07,215905022,Kamielea,I had a lot of fun staying at this Airbnb. Ale...
760804,972841948082325213,976174894758092447,2023-09-08,231329188,S,What a delightful space to enjoy! We came as a...
760805,973108526049311119,978404137437934537,2023-09-11,506879501,Chani,Very clean and the host had great communicatio...
760806,973285217121157648,982748425442699644,2023-09-17,508950257,Esrom,Good location and price. Able to reach all the...

In [6]:
value2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760807 entries, 0 to 760806
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   listing_id     760807 non-null  object
 1   id             760807 non-null  int64
 2   last_updated   760807 non-null  datetime64[ns]
 3   reviewer_id    760807 non-null  int64
 4   reviewer_name  760807 non-null  object
 5   comments       760807 non-null  object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 34.8+ MB

In [1]:
from database_handler import create_connection
from lookups import DestSchema
from prehook import execute_sql_folder_prehook
db_session = create_connection()
execute_sql_folder_prehook(db_session)

Connection is successful.

['V01_prehook_create_schema.sql']

In [2]:
from prehook import create_sql_staging_tables
from lookups import DestSchema, ETLStep
from database_handler import create_connection
db_session = create_connection()
create_sql_staging_tables(db_session=db_session, target_schema=DestSchema.DW_SCHEMA.value)

Connection is successful.

{'cleaned_df1': 'CREATE TABLE IF NOT EXISTS dw_reporting.STG_cleaned_df1 (\nlisting_id INTEGER, \nlisting_url TEXT, \nlast_updated TEXT, \nname TEXT, \ndescription TEXT, \npicture_url TEXT, \nhost_id INTEGER, \nhost_url TEXT, \nhost_name TEXT, \nhost_since TEXT, \nhost_location TEXT, \nhost_response_time TEXT, \nhost_response_rate TEXT, \nhost_neighbourhood TEXT, \nhost_total_listings_count TEXT, \nhost_identity_verified TEXT, \nneighbourhood TEXT, \nneighbourhood_view TEXT, \nlatitude FLOAT, \nlongitude FLOAT, \nproperty_type TEXT, \naccommodates INTEGER, \nbathrooms TEXT, \nbedrooms FLOAT, \nbeds FLOAT, \namenities TEXT, \nprice TEXT, \nminimum_nights INTEGER, \nmaximum_nights INTEGER, \nhas_availability TEXT, \navailability_30 INTEGER, \navailability_365 INTEGER, \nnumber_of_reviews INTEGER, \nfirst_review TIMESTAMP, \nlast_review TIMESTAMP, \nreview_scores_rating FLOAT, \ninstant_bookable TEXT, \nreviews_per_month FLOAT\n);',
 'cleaned_df2': 'CREATE TABLE IF NOT EXISTS dw_reporting.STG_cleaned_df2 (\nlisting_id INTEGER, \nid INTEGER, \ndate TEXT, \nreviewer_id INTEGER, \nreviewer_name TEXT, \ncomments TEXT\n);'}

In [2]:
from pandas_handler import dataframes_cleansed
dataframes_cleansed()

Error returning the cleaned dataframes! = Unknown string format: unspecified present at position 0

{}

In [2]:
from database_handler import read_data_as_dataframe
from lookups import InputTypes
import pandas as pd
import numpy as np  # Import numpy for calculations

# Read the CSV file
file_path = r'csv_files\listings.csv'  # Use raw string for Windows file path
df = read_data_as_dataframe(InputTypes.CSV, file_path)
df

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,6,https://www.airbnb.com/rooms/6,20230918050343,2023-09-18,previous scrape,Home in San Diego · ★4.81 · 3 bedrooms · 3 bed...,"You read that right, this craftsman home was t...","We have the best Neighborhood in San Diego, in...",https://a0.muscache.com/pictures/miso/Hosting-...,29,...,4.97,4.77,4.80,"STR-04545L, 631067",f,1,1,0,0,0.82
1,29967,https://www.airbnb.com/rooms/29967,20230918050343,2023-09-18,city scrape,Bungalow in San Diego · ★4.77 · 2 bedrooms · 3...,"This 2 bedroom, 2 full bathroom home offers al...",NaN,https://a0.muscache.com/pictures/76103867/c9b5...,129123,...,4.92,4.81,4.76,"STR-05218L, 645110",f,5,5,0,0,0.63
2,54001,https://www.airbnb.com/rooms/54001,20230918050343,2023-09-18,city scrape,Guesthouse in La Jolla · ★4.94 · 2 bedrooms · ...,"Off the beaten path: 4 garden areas, 2 garde...","Tranquility, stately trees, meditative, zen-fu...",https://a0.muscache.com/pictures/miso/Hosting-...,252692,...,4.97,4.97,4.89,"STR-05706L, 523003",f,1,1,0,0,2.04
3,62274,https://www.airbnb.com/rooms/62274,20230918050343,2023-09-18,city scrape,Guesthouse in San Diego · ★4.77 · 1 bedroom · ...,"Modern, cozy, artsy, and european in a lush ga...","We are in walking distance to Starbucks, Trade...",https://a0.muscache.com/pictures/84577734/93ca...,302986,...,4.86,4.87,4.79,"STR-00821L, 520121",f,3,2,1,0,5.31
4,75668,https://www.airbnb.com/rooms/75668,20230918050343,2023-09-18,city scrape,Condo in San Diego · ★4.83 · 1 bedroom · 1 bed...,<b>The space</b><br />Medium large bedroom wit...,NaN,https://a0.muscache.com/pictures/555077/d489e7...,401936,...,4.89,4.80,4.87,NaN,f,2,0,2,0,1.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12492,975626784766085577,https://www.airbnb.com/rooms/975626784766085577,20230918050343,2023-09-18,city scrape,Rental unit in San Diego · ★New · 1 bedroom · ...,Welcome to our centrally located place in the ...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,456697664,...,NaN,NaN,NaN,Exempt,t,76,76,0,0,NaN
12493,975645593399245481,https://www.airbnb.com/rooms/975645593399245481,20230918050343,2023-09-18,city scrape,Home in San Diego · ★New · 4 bedrooms · 4 beds...,"This special place is close to everything, mak...",NaN,https://a0.muscache.com/pictures/a851c04a-0224...,20373580,...,NaN,NaN,NaN,Exempt,f,2,2,0,0,NaN
12494,975905015986457757,https://www.airbnb.com/rooms/975905015986457757,20230918050343,2023-09-18,city scrape,Home in San Diego · ★New · 1 bedroom · 1 bed ·...,Forget your worries in this spacious and seren...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,46637397,...,NaN,NaN,NaN,"STR-01741L, 641593",t,5,2,3,0,NaN
12495,976129491368742667,https://www.airbnb.com/rooms/976129491368742667,20230918050343,2023-09-18,city scrape,Rental unit in San Diego · ★New · 2 bedrooms ·...,Enjoy a stylish experience at this centrally-l...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,280198638,...,NaN,NaN,NaN,Exempt,f,3,3,0,0,NaN
12496,976138831185478864,https://www.airbnb.com/rooms/976138831185478864,20230918050343,2023-09-18,city scrape,Home in San Diego · ★New · 4 bedrooms · 4 baths,"Amazing 3BD + 1BD House in the Heart of PB, wi...",NaN,https://a0.muscache.com/pictures/prohost-api/H...,2772383,...,NaN,NaN,NaN,"STR-01975L, 636743",t,47,47,0,0,NaN

In [3]:
from database_handler import read_data_as_dataframe
from lookups import InputTypes
import pandas as pd
import numpy as np  # Import numpy for calculations

# Read the CSV file
file_path = r'csv_files\listings.csv'  # Use raw string for Windows file path
df = read_data_as_dataframe(InputTypes.CSV, file_path)

# Drop unwanted columns
columns_to_drop = [
    'scrape_id', 'source', 'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
    'host_listings_count', 'host_has_profile_pic', 'neighbourhood_group_cleansed', 'bathrooms', 'calendar_updated',
    'number_of_reviews_ltm', 'number_of_reviews_l30d', 'calendar_last_scraped', 'review_scores_accuracy',
    'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location',
    'review_scores_value', 'host_about', 'neighborhood_overview',
    'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights',
    'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'license', 'host_verifications', 'property_type',
    'availability_60', 'availability_90', 'calculated_host_listings_count',
    'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms',
    'calculated_host_listings_count_shared_rooms'
    
]
df = df.drop(columns=columns_to_drop)

# Rename columns
column_mapping = {
    'last_scraped': 'last_updated', 'name' : 'listing_name', 'id': 'listing_id', 'neighbourhood_cleansed': 'neighbourhood_view',
    'room_type': 'property_type', 'bathrooms_text': 'bathrooms', 'description' : 'listing_description'
}
df = df.rename(columns=column_mapping)

# Extract the first part of 'name' column
df['listing_name'] = df['listing_name'].str.split('·').str.get(0).str.strip()

# Clean the 'description' column
df['listing_description'] = df['listing_description'].str.replace('<br />', '').str.replace('<b>', '').replace('</b>', '')

# Fill missing values
columns_to_fill = [
    'listing_description', 'host_name', 'host_since', 'host_total_listings_count', 'host_identity_verified', 'host_location',
    'host_response_time', 'host_response_rate', 'host_neighbourhood'
]
df[columns_to_fill] = df[columns_to_fill].fillna('unspecified')

# Apply neighborhood mapping
neighbourhood_mapping = {
    'San Diego , California, United States': 'San Diego, California, United States',
    'San diego, California, United States': 'San Diego, California, United States',
    'San Diego, Ca, United States': 'San Diego, California, United States',
    'San Diego County, California, United States': 'San Diego, California, United States',
    'San Diego, United States': 'San Diego, California, United States',
    'San Diego , Ca, United States': 'San Diego, California, United States',
    ' San Diego, California, United States': 'San Diego, California, United States',
    'SAN DIEGO, California, United States': 'San Diego, California, United States',
    'La Jolla, California, United States': 'La Jolla, San Diego, United States',
    'LA JOLLA, California, United States': 'La Jolla, San Diego, United States',
    'La Jolla , California, United States': 'La Jolla, San Diego, United States',
    'Mission Bay, California, United States': 'Mission Beach, California, United States',
    'La Jolla Cove, California, United States': 'La Jolla, San Diego, United States',
    'LA JOLLA, CALIFORNIA, United States': 'La Jolla, San Diego, United States',
    ' La Jolla, California, United States': 'La Jolla, San Diego, United States',
    'CA, United States': 'California, United States',
    'California, South Dakota, United States': 'California, United States'
}
df['neighbourhood'] = df['neighbourhood'].map(neighbourhood_mapping).fillna('San Diego, California, United States')

# Fill missing values with mean rating and convert to datetime
df['review_scores_rating'].fillna(df['review_scores_rating'].mean(), inplace=True)
df['reviews_per_month'].fillna(0, inplace=True)
df['first_review'] = pd.to_datetime(df['first_review'], errors='coerce').fillna(0)
df['last_review'] = pd.to_datetime(df['last_review'], errors='coerce').fillna(0)

# Fill remaining missing values
df[['bathrooms', 'bedrooms', 'beds']] = df[['bathrooms', 'bedrooms', 'beds']].fillna(0)
df['host_since'] = pd.to_datetime(df['host_since'], errors='coerce')

# Convert listing_id to object type
df['listing_id'] = df['listing_id'].astype('object')

df

,listing_id,listing_url,last_updated,listing_name,listing_description,picture_url,host_id,host_url,host_name,host_since,...,maximum_nights,has_availability,availability_30,availability_365,number_of_reviews,first_review,last_review,review_scores_rating,instant_bookable,reviews_per_month
0,6,https://www.airbnb.com/rooms/6,2023-09-18,Home in San Diego,"You read that right, this craftsman home was t...",https://a0.muscache.com/pictures/miso/Hosting-...,29,https://www.airbnb.com/users/show/29,Sara,2008-03-03,...,30,t,0,0,153,2008-06-22 00:00:00,2019-09-14 00:00:00,4.810000,f,0.82
1,29967,https://www.airbnb.com/rooms/29967,2023-09-18,Bungalow in San Diego,"This 2 bedroom, 2 full bathroom home offers al...",https://a0.muscache.com/pictures/76103867/c9b5...,129123,https://www.airbnb.com/users/show/129123,Michael,2010-05-21,...,365,t,14,286,102,2010-07-09 00:00:00,2023-08-25 00:00:00,4.770000,f,0.63
2,54001,https://www.airbnb.com/rooms/54001,2023-09-18,Guesthouse in La Jolla,"Off the beaten path: 4 garden areas, 2 garde...",https://a0.muscache.com/pictures/miso/Hosting-...,252692,https://www.airbnb.com/users/show/252692,Marsha,2010-10-04,...,365,t,0,99,316,2011-01-04 00:00:00,2023-09-01 00:00:00,4.940000,f,2.04
3,62274,https://www.airbnb.com/rooms/62274,2023-09-18,Guesthouse in San Diego,"Modern, cozy, artsy, and european in a lush ga...",https://a0.muscache.com/pictures/84577734/93ca...,302986,https://www.airbnb.com/users/show/302986,Isabel,2010-11-28,...,14,t,1,273,826,2010-12-05 00:00:00,2023-09-03 00:00:00,4.770000,f,5.31
4,75668,https://www.airbnb.com/rooms/75668,2023-09-18,Condo in San Diego,The space</b>Medium large bedroom with a queen...,https://a0.muscache.com/pictures/555077/d489e7...,401936,https://www.airbnb.com/users/show/401936,Johnathon,2011-02-20,...,1825,t,0,103,198,2011-07-25 00:00:00,2022-11-26 00:00:00,4.830000,f,1.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12492,975626784766085577,https://www.airbnb.com/rooms/975626784766085577,2023-09-18,Rental unit in San Diego,Welcome to our centrally located place in the ...,https://a0.muscache.com/pictures/miso/Hosting-...,456697664,https://www.airbnb.com/users/show/456697664,Aarti,2022-04-29,...,365,t,4,15,0,0,0,4.777629,t,0.00
12493,975645593399245481,https://www.airbnb.com/rooms/975645593399245481,2023-09-18,Home in San Diego,"This special place is close to everything, mak...",https://a0.muscache.com/pictures/a851c04a-0224...,20373580,https://www.airbnb.com/users/show/20373580,Celine,2014-08-21,...,365,t,22,22,0,0,0,4.777629,f,0.00
12494,975905015986457757,https://www.airbnb.com/rooms/975905015986457757,2023-09-18,Home in San Diego,Forget your worries in this spacious and seren...,https://a0.muscache.com/pictures/miso/Hosting-...,46637397,https://www.airbnb.com/users/show/46637397,Ken,2015-10-15,...,365,t,16,17,0,0,0,4.777629,t,0.00
12495,976129491368742667,https://www.airbnb.com/rooms/976129491368742667,2023-09-18,Rental unit in San Diego,Enjoy a stylish experience at this centrally-l...,https://a0.muscache.com/pictures/miso/Hosting-...,280198638,https://www.airbnb.com/users/show/280198638,Travel And Luxury,2019-07-28,...,365,t,28,88,0,0,0,4.777629,f,0.00
12496,976138831185478864,https://www.airbnb.com/rooms/976138831185478864,2023-09-18,Home in San Diego,"Amazing 3BD + 1BD House in the Heart of PB, wi...",https://a0.muscache.com/pictures/prohost-api/H...,2772383,https://www.airbnb.com/users/show/2772383,San Diego,2012-06-28,...,365,t,26,324,0,0,0,4.777629,t,0.00

In [4]:
df['price'] = df['price'].str.replace('[\$,]', '', regex=True)

In [5]:
df['price'] = pd.to_numeric(df['price'])

In [6]:
df['price'].describe()

count    12497.000000
mean       292.973754
std        989.767257
min         10.000000
25%        119.000000
50%        183.000000
75%        314.000000
max      90223.000000
Name: price, dtype: float64

In [1]:
from pandas_handler import dataframes_cleansed
dataframes_cleansed()

{}

In [3]:
from database_handler import create_connection
create_connection()

Connection is successful.

In [1]:
from prehook import execute_prehook
execute_prehook()

Connection is successful.
Prehook SQL Commands were successfully executed!
First dataframe was executed
Second dataframe was executed!
Data cleaning and optimization is fully complete!
The create staging table statement was successfully executed!
Staging tables index was created!
The create staging table statement was successfully executed!
Staging tables index was created!
Connection is closed.

In [2]:
from hook import execute_hook
execute_hook()

Connection is successful.

c:\Users\HP i5\Desktop\SE_Factory\FSD-Final-Project\database_handler.py:55: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return_dataframe = pd.read_sql_query(con= db_session, sql= file_path)

First dataframe was executed
Second dataframe was executed!
Data was successfully inserted into staging tables.
Sentiment Column in SQL was updated
sentiment analsyis applied!
Data was successfully inserted into staging tables.
Connection is closed.

In [3]:
from posthookk import execute_posthook
execute_posthook()

Connection is successful.
Table dw_reporting.stg_cleaned_df1 truncated successfully.
Table dw_reporting.stg_cleaned_df2 truncated successfully.
Connection is closed.

In [3]:
from hook import return_etl_last_updated_date, create_etl_checkpoint
from lookups import DestSchema
from database_handler import create_connection
db_session = create_connection()
create_etl_checkpoint(DestSchema.DW_SCHEMA, db_session)
etl_date, etl_time_exists = return_etl_last_updated_date(db_session)

Connection is successful.

c:\Users\HP i5\Desktop\SE_Factory\FSD-Final-Project\database_handler.py:55: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return_dataframe = pd.read_sql_query(con= db_session, sql= file_path)

In [4]:
from hook import insert_into_stg_tables
from database_handler import create_connection
from lookups import DestSchema
db_session = create_connection()
insert_into_stg_tables(db_session, DestSchema.DW_SCHEMA.value, etl_date)

Connection is successful.
Column was added
sentiment analsyis applied in python

["Inserted new data after '1900-01-01 00:00:00' into stg_cleaned_df1 successfully.",
 "Inserted new data after '1900-01-01 00:00:00' into stg_cleaned_df2 successfully."]

In [5]:
from hook import execute_sql_folder_hook
execute_sql_folder_hook(db_session)

In [ ]:
from hook import insert_or_update_etl_checkpoint
insert_or_update_etl_checkpoint(db_session, etl_time_exists=etl_time_exists)

In [1]:
from hook import *
execute_hook()

Connection is successful.

c:\Users\HP i5\Desktop\SE_Factory\FSD-Final-Project\database_handler.py:55: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return_dataframe = pd.read_sql_query(con= db_session, sql= file_path)

Column was added
sentiment analsyis applied in python
Connection is closed.

In [6]:
from pandas_handler import dataframes_cleansed 
mydict = dataframes_cleansed()

In [10]:
df = mydict['cleaned_df1']

In [16]:
df.head()

,listing_id,listing_url,last_updated,listing_name,listing_description,picture_url,host_id,host_url,host_name,host_since,...,maximum_nights,has_availability,availability_30,availability_365,number_of_reviews,first_review,last_review,review_scores_rating,instant_bookable,reviews_per_month
0,6,https://www.airbnb.com/rooms/6,2023-09-18,Home in San Diego,"You read that right, this craftsman home was t...",https://a0.muscache.com/pictures/miso/Hosting-...,29,https://www.airbnb.com/users/show/29,Sara,2008-03-03,...,30,t,0,0,153,2008-06-22 00:00:00,2019-09-14 00:00:00,4.81,f,0.82
1,29967,https://www.airbnb.com/rooms/29967,2023-09-18,Bungalow in San Diego,"This 2 bedroom, 2 full bathroom home offers al...",https://a0.muscache.com/pictures/76103867/c9b5...,129123,https://www.airbnb.com/users/show/129123,Michael,2010-05-21,...,365,t,14,286,102,2010-07-09 00:00:00,2023-08-25 00:00:00,4.77,f,0.63
2,54001,https://www.airbnb.com/rooms/54001,2023-09-18,Guesthouse in La Jolla,"Off the beaten path: 4 garden areas, 2 garde...",https://a0.muscache.com/pictures/miso/Hosting-...,252692,https://www.airbnb.com/users/show/252692,Marsha,2010-10-04,...,365,t,0,99,316,2011-01-04 00:00:00,2023-09-01 00:00:00,4.94,f,2.04
3,62274,https://www.airbnb.com/rooms/62274,2023-09-18,Guesthouse in San Diego,"Modern, cozy, artsy, and european in a lush ga...",https://a0.muscache.com/pictures/84577734/93ca...,302986,https://www.airbnb.com/users/show/302986,Isabel,2010-11-28,...,14,t,1,273,826,2010-12-05 00:00:00,2023-09-03 00:00:00,4.77,f,5.31
4,75668,https://www.airbnb.com/rooms/75668,2023-09-18,Condo in San Diego,The space</b>Medium large bedroom with a queen...,https://a0.muscache.com/pictures/555077/d489e7...,401936,https://www.airbnb.com/users/show/401936,Johnathon,2011-02-20,...,1825,t,0,103,198,2011-07-25 00:00:00,2022-11-26 00:00:00,4.83,f,1.34

In [13]:
df['price'].max()

90223.0

In [14]:
df.loc[df['price'] == 90223.0, :]

,listing_id,listing_url,last_updated,listing_name,listing_description,picture_url,host_id,host_url,host_name,host_since,...,maximum_nights,has_availability,availability_30,availability_365,number_of_reviews,first_review,last_review,review_scores_rating,instant_bookable,reviews_per_month
8426,671174623571305139,https://www.airbnb.com/rooms/671174623571305139,2023-09-18,Guest suite in Chula Vista,Family & pet friendly 2 bedroom place. The bea...,https://a0.muscache.com/pictures/9645a925-c8d6...,477983965,https://www.airbnb.com/users/show/477983965,Shawnee,2022-09-03,...,180,t,0,0,18,2022-09-05 00:00:00,2023-07-18 00:00:00,4.89,t,1.42

In [15]:
df.loc[df['price'] == 50000, :]

,listing_id,listing_url,last_updated,listing_name,listing_description,picture_url,host_id,host_url,host_name,host_since,...,maximum_nights,has_availability,availability_30,availability_365,number_of_reviews,first_review,last_review,review_scores_rating,instant_bookable,reviews_per_month
2074,20501856,https://www.airbnb.com/rooms/20501856,2023-09-18,Rental unit in San Diego,This 1 bedroom is located on the strand in the...,https://a0.muscache.com/pictures/ce8b9b51-ef59...,4657890,https://www.airbnb.com/users/show/4657890,William,2013-01-10,...,1125,t,0,136,242,2017-08-20 00:00:00,2022-09-21 00:00:00,4.41,f,3.27

In [20]:
print(df['first_review'].dtypes)

object

In [1]:
from prehook import *
execute_prehook()

Connection is successful.
First dataframe was executed
Second dataframe was executed!
Connection is closed.